- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Dolphin.Generator.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/Mednafen.Controllers.cs
- emulatorLauncher/Generators/Mednafen.Generator.cs
- emulatorLauncher/Generators/Yuzu.Generator.cs
- emulatorLauncher/emulatorLauncher.csproj
- yuzu : ASTC compression
- dolphin : vertex rounding
- beetle_psx_hw : overclocking
> Add requested features (yuzu, dolphin, beetle_psx_hw)

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Flycast.Controllers.cs
- emulatorLauncher/Generators/Flycast.Generator.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
> Flycast controllers - end

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Cemu.Generator.cs
- emulatorLauncher/Generators/Flycast.Controllers.cs
- emulatorLauncher/Generators/Mesen.Controllers.cs
- emulatorLauncher/Generators/Mesen.Generator.cs
- emulatorLauncher/emulatorLauncher.csproj
> Mesen controllers

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/PinballFX.Generator.cs
- emulatorLauncher/Program.cs
- emulatorLauncher/emulatorLauncher.csproj
- new generator to launch both Pinball FX 3 and the new Pinball FX 2023 with steam or with non steam version
> new generator for pinballfx and pinballfx3

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Duckstation.Generator.cs
- emulatorLauncher/Generators/Flycast.Generator.cs
- emulatorLauncher/Generators/LibRetro.Generator.cs
- emulatorLauncher/Generators/Libretro.Controllers.cs
> Fix hard sync feature in retroarch

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Duckstation.Controllers.cs
- emulatorLauncher/Generators/Flycast.Controllers.cs
- emulatorLauncher/Generators/LibRetro.Guns.cs
- emulatorLauncher/Generators/Model3.Controllers.cs
- emulatorLauncher/Generators/Pcsx2.Controllers.cs
- Supermodel
- mednafen_psx_hw
> More guns - part 2

- emulatorLauncher/Generators/Fpinball.Generator.cs
> Fix fpinball

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Bizhawk.Controllers.cs
- emulatorLauncher/Generators/Bizhawk.CoreOptions.cs
- emulatorLauncher/Generators/Bizhawk.Generator.cs
- emulatorLauncher/Generators/Bizhawk.Guns.cs
- emulatorLauncher/Installer.cs
- emulatorLauncher/Program.cs
- emulatorLauncher/emulatorLauncher.csproj
> Add bizhawk to emulatorlauncher

- .emulationstation/es_features.cfg
- emulatorLauncher/Common/Generator.cs
- emulatorLauncher/Common/SimpleBml.cs
- emulatorLauncher/Generators/Ares.Generator.cs
- emulatorLauncher/Installer.cs
- emulatorLauncher/Program.cs
- emulatorLauncher/emulatorLauncher.csproj
Missing controller autoconfiguration, to come !
> Add Ares generator

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Bizhawk.Controllers.cs
- emulatorLauncher/Generators/Bizhawk.CoreOptions.cs
- emulatorLauncher/Generators/Bizhawk.Generator.cs
atari 2600, 7800, lynx, jaguar, apple2 and colecovision
> Bizhawk - next batch of systems

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Xemu.Generator.cs
- add bezel and shaderset features
- disable bezel if is widescreen
- add show menu feature (default : disabled)
- windowed mode if ES is windowed
> add bezel and shaderset features

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Citra.Generator.cs
- emulatorLauncher/Generators/Dolphin.Controllers.cs
- emulatorLauncher/Generators/Dolphin.Generator.cs
- emulatorLauncher/Generators/Flycast.Controllers.cs
- emulatorLauncher/Generators/Jynx.Generator.cs
- emulatorLauncher/Generators/Model2.Controllers.cs
- emulatorLauncher/Generators/Model2.Generator.cs
- emulatorLauncher/Generators/ZEsarUX.Controllers.cs
- emulatorLauncher/emulatorLauncher.csproj
m2 : add deadzone setting & controller autoconfig
citra : add video driver option
play : add controller configuration from user files
dolphin : add motion and fix PS5 Controller name
flycast : enhance button mapping for service and test
> Citra, model2, dolphin, flycast, play

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Xm6pro.Generator.cs
- emulatorLauncher/Installer.cs
- emulatorLauncher/Program.cs
- emulatorLauncher/emulatorLauncher.csproj
add compatibility for XM6 Pro emulator
features are WIP
> add XM6 Pro emulator for X68000 (initial commit)

- emulatorLauncher/Generators/Mednafen.Generator.cs
use foreach pair in dictionary as a loop instead of method for paths injection
> paths injection refactorisation

- emulatorLauncher/Generators/LibRetro.Generator.cs
> Fix small language issue when coming back to EN from another language

- emulatorLauncher/Generators/Flycast.Controllers.cs
- emulatorLauncher/Generators/Flycast.Generator.cs
> Flycast - map exit to ESC keyboard

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Mednafen.Controllers.cs
- emulatorLauncher/Generators/Mednafen.Generator.cs
> mednafen fix controller apple 2 and command lines

- .emulationstation/es_features.cfg
> Remove cheevos from mame core

- emulatorLauncher/Generators/ZEsarUX.Generator.cs
> ZesarUX - add management of zip files

- emulatorLauncher/Bezels/BezelFiles.cs
- emulatorLauncher/Reshader/ReshadeManager.cs
when decorations are set to none -> We still must have a border
> [Sinden Border/ReshadeManager/BezelFiles] Fix sinden border management

- EmulatorLauncher.Common/FileTools.cs
- EmulatorLauncher.Common/ScreenCapture.cs
- emulatorLauncher/Common/ScreenShotsWatcher.cs
- emulatorLauncher/Generators/Fpinball.Generator.cs
- emulatorLauncher/Generators/LibRetro.Generator.cs
- emulatorLauncher/Generators/VPinball.Generator.cs
- emulatorLauncher/emulatorLauncher.csproj
> [ScreenShotWatcher] Assign image to gamelist when a screenshot is taken, if the game has no image ( fpinball / vpinball / libretro )

- EmulatorLauncher.Common/FileTools.cs
- emulatorLauncher/Generators/LibRetro.Generator.cs
- emulatorLauncher/Generators/LibRetro.StateFileManager.cs
- emulatorLauncher/Generators/Phoenix.Generator.cs
+ Fix .auto savestate created when launching a game.
+ Refactor some methods into FileTools
> [Libretro/Retroachivements/SaveStates] Disable hardcore mode if launching from a savestate.

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Kronos.Controllers.cs
- emulatorLauncher/Generators/Kronos.Generator.cs
- emulatorLauncher/Installer.cs
- emulatorLauncher/Program.cs
- emulatorLauncher/emulatorLauncher.csproj
Without controller autoconfiguration
> Added kronos

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- Dosbox cpu_core and cpu_type reverted + ram + aspect ratio
- puae and vice : crop options
- sprite limit alignment
> Few libretro core options fixes

- .emulationstation/es_features.cfg
> Dolphin - add shader compilation method

- EmulatorLauncher.Common/EmulationStation/GunGames.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Program.cs
See https://github.com/batocera-linux/batocera-emulationstation/pull/1652
For now it's still retrocompatible with gungames.xml if gamesdb.xml is missing.
> [GamesDB] Adapation of GunGames to read gamesdb.xml which is the new format

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Citra.Generator.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/Redream.Generator.cs
Fixes:
- citra language change (fix byte in nand)
- lr-flycast default region
Enhancements:
- Add redream resolutions choice
> 2 fixes (citra & lr-flycast) + 1 enhancement (redream)

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/GzDoom.Generator.cs
- emulatorLauncher/Generators/Model3.Generator.cs
- Fix supermodel vsync and add features
- Add gzdoom crosshairs
> Supermodel and gzdoom

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Dolphin.Generator.cs
- emulatorLauncher/Generators/Rpcs3.Generator.cs
- emulatorLauncher/Generators/Xenia.Generator.cs
- dolphin: path to IPL
- xenia and rpcs3: depends on desktop resolution
- fix genesis_plus_gx cpu overclock option
> Small fixes

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Model2.Controllers.cs
- emulatorLauncher/Generators/Model3.Controllers.cs
- emulatorLauncher/Generators/Zinc.Generator.cs
Zinc : add frameskipping
Model3 : fix dolphinbar presence
Model2 : add option to use joypad for credit and start
> Model2, model3 and zinc

- emulatorLauncher/Generators/Fpinball.Generator.cs
- emulatorLauncher/Generators/VPinball.Generator.cs
- emulatorLauncher/PadToKey/JoystickListener.cs
- emulatorLauncher/PadToKey/PadToKey.cs
+ perform screen capture with hotkey+r3 with vpinball/fpinball ( like with the printscreen key )
> [PadToKey] Allow actions in registered bindings

- .emulationstation/es_features.cfg
- emulatorLauncher/Common/Wheels.cs
- emulatorLauncher/Generators/Bizhawk.Controllers.cs
- emulatorLauncher/Generators/Bizhawk.Generator.cs
- emulatorLauncher/Generators/Flycast.Controllers.cs
- emulatorLauncher/Generators/Flycast.Wheels.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Resources/wheelSDLMapping.yml
- emulatorLauncher/emulatorLauncher.csproj
- Flycast wheels
- Fix some libretro ppsspp features
> Libretro ppsspp features + flycast wheels

- .emulationstation/es_features.cfg
- EmulatorLauncher.Common/Joysticks/RawInputDevice.cs
- EmulatorLauncher.Common/Joysticks/SdlJoystickGuid.cs
- EmulatorLauncher.Common/SDL2.cs
- emulatorLauncher/Common/Wheels.cs
- emulatorLauncher/Generators/Dolphin.Controllers.cs
- emulatorLauncher/Generators/Flycast.Controllers.cs
- emulatorLauncher/Generators/Flycast.Wheels.cs
- emulatorLauncher/Generators/Mame64.Controllers.cs
- emulatorLauncher/Generators/Mame64.Generator.cs
- emulatorLauncher/Generators/Model2.Controllers.cs
- emulatorLauncher/Generators/Model3.Controllers.cs
- emulatorLauncher/Generators/Ryujinx.Controllers.cs
- emulatorLauncher/Generators/Ryujinx.Generator.cs
- emulatorLauncher/Resources/wheelMapping.yml
- emulatorLauncher/Resources/wheelSDLMapping.yml
- emulatorLauncher/emulatorLauncher.csproj
Wheels:
- Add G923 and Driving force GT
- Add flycast standalone wheels config
SDL2 : add version 2.30 and method to get rawinput information and compute new GUID
> Wheels + ryujinx SDL2 guid fix (and for other emulators using new CRC in guid)

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Cemu.Controllers.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/LibRetro.Generator.cs
- emulatorLauncher/Generators/OpenBor.Generator.cs
- emulatorLauncher/Generators/Zinc.Controllers.cs
- emulatorLauncher/Generators/Zinc.Generator.cs
- emulatorLauncher/Installer.cs
- cemu button inversion
- hatarib gemdos folder launch (will need wiki explanation)
- eka2l1 in installer.cs
- zinc controllers
> Multiple fixes

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Dolphin.Controllers.cs
- emulatorLauncher/Generators/Model2.Generator.cs
- emulatorLauncher/Generators/ScummVm.Generator.cs
- emulatorLauncher/Generators/vita3k.Generator.cs
- Add model 2 crosshair feature
- dolphin : add hide wiimote pointer option and profile to use real lightgun for shooters
- Add 2 vita3k features
- scummvm : add method to manage game-specific data options in scummvm.ini
> Several enhancements model2, dolphin, vita3k, scummvm

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
Original gameboy had no color !
> gambatte : remove default colorization on gameboy

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/Libretro.Controllers.cs
- emulatorLauncher/Generators/Mame64.Controllers.cs
- emulatorLauncher/Generators/Model3.Controllers.cs
- emulatorLauncher/Generators/PSXMame.Controllers.cs
- emulatorLauncher/Generators/PSXMame.Generator.cs
- emulatorLauncher/Installer.cs
- emulatorLauncher/Program.cs
- emulatorLauncher/emulatorLauncher.csproj
- add mednafen_psx_hw feature
- mame controller order
- psxmame addition
- libretro remaps enabled even when autocontroller configuration is disabled
- gun option added to some mame cores
- model3 wheels stuff
> libretro features + PSXMame

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Dolphin.Controllers.cs
- emulatorLauncher/Generators/Mednafen.Controllers.cs
- emulatorLauncher/Generators/Model3.Generator.cs
- emulatorLauncher/Installer.cs
- Supermodel : add supersampling
- Magic Engine : add to installer
- Mednafen : fix constroller indexes
- Dolphin : Gamecube : add raphnet and mayflash adapter management
> Supermodel, magic engine, mednafen & dolphin

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/ExeLauncher.Generator.cs
- emulatorLauncher/Program.cs
Ikemen GO is an open source fighting game engine that supports resources from the MUGEN engine.
> add ikemen features

- .emulationstation/es_features.cfg
- EmulatorLauncher.Common/Joysticks/RawInputDevice.cs
- EmulatorLauncher.Common/Joysticks/SdlJoystickGuid.cs
- emulatorLauncher/Generators/Mame64.Controllers.cs
- VPinball : add pad2key
- MAME64 : fix gamepad order
- SDLJoystick : fix guid for ryujinx and cemu when ctrl.Name = ""
> VPINBALL, MAME64 and SDLJoystick GUID

- emulatorLauncher/Generators/Cxbx.Generator.cs
- emulatorLauncher/Generators/Fpinball.Generator.cs
Fix FPINBALL features
Chihiro fullscreen when xbe file
> Fixes fpinball cxbx

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Cxbx.Generator.cs
- emulatorLauncher/Generators/Dolphin.Generator.cs
- emulatorLauncher/Generators/Fbneo.Controllers.cs
- emulatorLauncher/Generators/Mame64.Controllers.cs
- emulatorLauncher/Generators/Mame64.Generator.cs
- emulatorLauncher/Generators/Rpcs3.Controllers.cs
- Chihiro fullscreen management with CXBX
- MAME simplification of multigun
- RPCS3 option to force SDL for Xinput controller
- FBNEO standalone additional control layouts
- Dolphin : do not force borderless fullscreen to off if no bezels
> Multiple fixes & enhancements post v6.1

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
> add pocketcdg core compatibility

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Cemu.Controllers.cs
- emulatorLauncher/Generators/Demul.Generator.cs
- emulatorLauncher/Generators/ExeLauncher.Generator.cs
- emulatorLauncher/Generators/Fbneo.Controllers.cs
- emulatorLauncher/Generators/MessSystem.cs
- cemu: add XINPUT
- FBNEO : add mappings
- Add CAVE to demul
- Add slot options for some MESS systems
> Multiple enhancements

- emulatorLauncher/Generators/Fbneo.Controllers.cs
For cfg files that do not have P1 or P2 in the button label
> Manage controller mapping for FBNEO in a more flexible way with yml file

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Citra.Generator.cs
- emulatorLauncher/Generators/Lime3ds.Generator.cs
> Citra and Lime features addition

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Mame64.Generator.cs
- emulatorLauncher/Generators/Model3.Generator.cs
> Add outputs to supermodel

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Duckstation.Generator.cs
- emulatorLauncher/Generators/Pcsx2.Generator.cs
- emulatorLauncher/Generators/Singe2.Generator.cs
> SINGE 2 controls, PCSX2 mouse cursor, Duckstation fixes / update

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Dolphin.Generator.cs
- emulatorLauncher/Generators/Singe2.Generator.cs
> Add cheevos to dolphin

- emulatorLauncher/Generators/Eka2l1.Controllers.cs
> EKA2L1 - fix controller index

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Jgenesis.Generator.cs
> Add nes zapper to jgenesis

- emulatorLauncher/Generators/Lime3ds.Generator.cs
- emulatorLauncher/Installer.cs
> Lime3ds new executable name

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
And fix overscan for FCEUMM
Fix #506
> FCEUMM and MESEN - turbo + core aspect ratio

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/BigPEmu.Generator.cs
- emulatorLauncher/Generators/Bizhawk.Generator.cs
- emulatorLauncher/Generators/Citra.Generator.cs
- emulatorLauncher/Generators/Dolphin.Generator.cs
- emulatorLauncher/Generators/Duckstation.Generator.cs
- emulatorLauncher/Generators/Jynx.Generator.cs
- emulatorLauncher/Generators/Lime3ds.Generator.cs
- emulatorLauncher/Generators/Mednafen.Generator.cs
- emulatorLauncher/Generators/Ppsspp.Generator.cs
- emulatorLauncher/Generators/Rpcs3.Generator.cs
> Add squashfs support to 3ds emulators

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Mupen64.Generator.cs
> Remove openGL ES option

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Flycast.Generator.cs
- emulatorLauncher/Generators/Xenia.Generator.cs
- emulatorLauncher/Installer.cs
> Update xenia and canary

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Model3.Controllers.cs
- emulatorLauncher/Generators/Model3.Generator.cs
- emulatorLauncher/Generators/Pcsx2.Generator.cs
- Model 3 gamepad index
- add pcsx2 speedhack
- feature description corrections
> Various fixes and corrections

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/LibRetro.Generator.cs
> Retroarch - add custom relay server option

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Pcsx2.Generator.cs
> PCSX2 - network options

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/CapriceForever.Generator.cs
- emulatorLauncher/Generators/Pcsx2.Controllers.cs
- emulatorLauncher/Installer.cs
- PCSX2 : add a mapping for driving games
- Dolphin : fix installer
- capriceforever : fix reading of m3u files when shared with cap32 and using autorun command !
> Various fixes

- emulatorLauncher/Generators/LibRetro.Generator.cs
- emulatorLauncher/Generators/Libretro.Controllers.cs
But set select + start as padtokey
> Libretro - do not set hotkey actions if no actions are defined

- emulatorLauncher/Generators/Citra.Generator.cs
- emulatorLauncher/Generators/Fpinball.Generator.cs
- emulatorLauncher/Generators/Libretro.InputRemap.cs
- emulatorLauncher/Generators/Lime3ds.Generator.cs
- emulatorLauncher/Generators/Pcsx2.Generator.cs
- emulatorLauncher/Installer.cs
> Multiple fixes & enhancements

- .emulationstation/es_features.cfg
- emulatorLauncher/Bezels/BezelFiles.Tattoos.cs
- emulatorLauncher/Generators/Ares.Controllers.cs
- emulatorLauncher/Generators/Bizhawk.Controllers.cs
- emulatorLauncher/Generators/Libretro.InputRemap.cs
- emulatorLauncher/Generators/Mupen64.Controllers.cs
- emulatorLauncher/Generators/Simple64.Controllers.cs
> n64 add a profile for controllers

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Xenia.Generator.cs
> xenia canary add draw resolution

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Cemu.Controllers.cs
- emulatorLauncher/Generators/Sudachi.Controllers.cs
- emulatorLauncher/Generators/Suyu.Controllers.cs
- emulatorLauncher/Generators/Yuzu.Controllers.cs
> Add deadzone for switch emulators

- .emulationstation/es_features.cfg
- emulatorLauncher/Bezels/BezelFiles.Tattoos.cs
- emulatorLauncher/Bezels/BezelFiles.cs
- emulatorLauncher/Generators/LibRetro.CoreOptions.cs
- emulatorLauncher/Generators/Model2.Generator.cs
- emulatorLauncher/Generators/Rpcs3.Controllers.cs
- emulatorLauncher/Generators/Rpcs3.Generator.cs
- emulatorLauncher/Generators/Yabasanshiro.Controllers.cs
- emulatorLauncher/Generators/Yabasanshiro.Generator.cs
- Fix yabasanshiro controllers
- model2 enhancements
- RPCS3 add option
- Add holani and noods cores
> Set of changes

- .emulationstation/es_features.cfg
- emulatorLauncher/Generators/Bizhawk.Guns.cs
- emulatorLauncher/Generators/Jgenesis.Controllers.cs
- emulatorLauncher/Generators/Jgenesis.Generator.cs
- emulatorLauncher/Generators/LibRetro.Guns.cs
- emulatorLauncher/Generators/ScummVm.Generator.cs
Fix #727 
Fix #728 
Fix #729 
Fix #730
> ScummVM, JGenesis, Bizhawk

- .emulationstation/es_features.cfg
- EmulatorLauncher.Common/Lightguns/RawLightGun.cs
- emulatorLauncher/Generators/Dolphin.Controllers.cs
- emulatorLauncher/Generators/Dolphin.Generator.cs
> Fix dolphin and add some lightguns to the database

- .emulationstation/es_features.cfg
- emulatorLauncher/Bezels/BezelFiles.Tattoos.cs
- emulatorLauncher/Generators/Mandarine.Controllers.cs
- emulatorLauncher/Generators/Mandarine.Generator.cs
- emulatorLauncher/Installer.cs
- emulatorLauncher/Program.cs
- emulatorLauncher/emulatorLauncher.csproj
> Add emulator

- emulatorLauncher/Generators/Dolphin.Controllers.cs
Thanks to stoffies | CHERRY XTRFY for identification
> Fix null pointer for dolphin-triforce with nintendo controller

- emulatorLauncher/Bezels/BezelFiles.Tattoos.cs
- emulatorLauncher/Generators/Libretro.InputRemap.cs
> geargrafx pad layouts

- EmulatorLauncher.Common/Launchers/SteamLibrary.cs
- EmulatorLauncher.Common/User32.cs
- emulatorLauncher/Generators/AmazonLauncher.Generator.cs
- emulatorLauncher/Generators/EpicLauncher.Generator.cs
- emulatorLauncher/Generators/ExeLauncher.Generator.cs
- emulatorLauncher/Generators/SteamLauncher.Generator.cs
- steam monitor in registry
- steam monitor through windows focus
> Steam - add aynshe changes

- .emulationstation/es_features.cfg
- emulatorLauncher/Common/Generator.cs
- emulatorLauncher/Common/Guns.cs
- emulatorLauncher/Controller.cs
- emulatorLauncher/Generators/Ares.Controllers.cs
- emulatorLauncher/Generators/Bizhawk.Controllers.cs
- emulatorLauncher/Generators/Dolphin.WiiControllers.cs
- emulatorLauncher/Generators/Eduke32.Generator.cs
- emulatorLauncher/Generators/Jgenesis.Controllers.cs
- emulatorLauncher/Generators/Libretro.Controllers.cs
- emulatorLauncher/Generators/Libretro.ControllersSpecial.cs
- emulatorLauncher/Generators/Mame64.Generator.cs
- emulatorLauncher/Generators/Mednafen.Controllers.cs
- emulatorLauncher/Generators/Mesen.Controllers.cs
- emulatorLauncher/Generators/Mesen.Generator.cs
- emulatorLauncher/Generators/MessSystem.cs
- emulatorLauncher/Generators/Model2.Generator.cs
- emulatorLauncher/Generators/Model3.Controllers.cs
- emulatorLauncher/Generators/Model3.Generator.cs
- emulatorLauncher/Generators/Rpcs3.Controllers.cs
- emulatorLauncher/Generators/Rpcs3.Generator.cs
- emulatorLauncher/Generators/SteamLauncher.Generator.cs
- emulatorLauncher/Generators/Ymir.Controllers.cs
- emulatorLauncher/Generators/Ymir.Generator.cs
- emulatorLauncher/PadToKey/JoyInputState.cs
> MAME add bios for segastv
